version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: repo-starter-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    volumes:
      - ./.sst/storage/postgres:/var/lib/postgresql/data
    restart: unless-stopped